/**
 * Resolve the LIVE GVR of the BuilderPublish claim CRD at publish time.
 *
 * WHY THIS IS NOT A CONSTANT: the BuilderPublish CRD is generated by core-provider from the
 * `builder-publish` composition (C1). Krateo derives a composition CRD's group + version from the
 * CHART, not from anything the frontend controls:
 *   • group   = `composition.krateo.io` (the shared Krateo composition group — NOT `apps.krateo.io`),
 *   • version = the chart version with dots→dashes, `v`-prefixed (e.g. builder-publish 1.7.17 →
 *               `v1-7-17`) — so it CHANGES on every builder-publish release,
 *   • plural  = `builderpublishes`.
 * Verified live on GKE krateo-057: the served path is
 * `/apis/composition.krateo.io/v1-7-17/namespaces/krateo-system/builderpublishes`.
 * A hardcoded GVR would 404 the instant the composition is re-released, so the frontend reads the
 * deployed CompositionDefinition's status and uses whatever version is actually served.
 */

import type { Config } from '../../context/ConfigContext'
import { getAccessToken } from '../../utils/getAccessToken'

import type { ApplyResourceSetGvr } from './applyResourceSet'

/** The CompositionDefinition (C1) whose status carries the generated BuilderPublish GVR. */
export const BUILDER_PUBLISH_COMPOSITION = 'builder-publish'
/** Stable parts of the generated GVR — group + plural do not track the chart version. */
export const BUILDER_PUBLISH_GROUP = 'composition.krateo.io'
export const BUILDER_PUBLISH_RESOURCE = 'builderpublishes'

/** The resolved GVR plus the matching `group/version` for the CR body's `apiVersion`. */
export interface ResolvedBuilderPublishGvr {
  gvr: ApplyResourceSetGvr
  apiVersion: string
}

/**
 * Extract group / resource / SERVED version from a builder-publish CompositionDefinition object.
 * Pure (unit-tested): returns null when no version is served yet (composition not reconciled), so
 * the caller denies rather than POSTing to a guessed version. group/resource fall back to the
 * known stable values if the status omits them (they never change), but the version never does.
 */
export const gvrFromCompositionDefinition = (compdef: unknown): ResolvedBuilderPublishGvr | null => {
  const status = (compdef as { status?: Record<string, unknown> } | null)?.status
  if (!status || typeof status !== 'object') {
    return null
  }
  const managed = status.managed as { group?: unknown; versionInfo?: unknown } | undefined
  const group = (typeof managed?.group === 'string' && managed.group) || BUILDER_PUBLISH_GROUP
  const resource = (typeof status.resource === 'string' && status.resource) || BUILDER_PUBLISH_RESOURCE
  const versions = Array.isArray(managed?.versionInfo) ? managed.versionInfo : []
  const served = versions.find((entry) => (entry as { served?: unknown })?.served === true) as { version?: unknown } | undefined
  if (typeof served?.version !== 'string' || served.version === '') {
    return null
  }
  return { apiVersion: `${group}/${served.version}`, gvr: { group, resource, version: served.version } }
}

/**
 * Resolve the BuilderPublish GVR by GETting the builder-publish CompositionDefinition over snowplow
 * `/call` (the SAME per-user, RBAC-bounded transport widgets use — the portal already reads
 * compositiondefinitions, so no new grant). Returns null on ANY failure (composition absent, not
 * yet reconciled, RBAC 403, snowplow 5xx, missing config) — a wrong-GVR POST must never be tried.
 */
export const resolveBuilderPublishGvr = async (config: Config | undefined): Promise<ResolvedBuilderPublishGvr | null> => {
  const snowplowBaseUrl = config?.api.SNOWPLOW_API_BASE_URL
  const namespace = config?.params.FRONTEND_NAMESPACE
  if (!snowplowBaseUrl || !namespace) {
    return null
  }
  try {
    const url = new URL(`${snowplowBaseUrl.replace(/\/+$/, '')}/call`)
    url.searchParams.set('resource', 'compositiondefinitions')
    url.searchParams.set('apiVersion', 'core.krateo.io/v1alpha1')
    url.searchParams.set('name', BUILDER_PUBLISH_COMPOSITION)
    url.searchParams.set('namespace', namespace)
    const headers: Record<string, string> = {}
    try {
      headers.Authorization = `Bearer ${getAccessToken()}`
    } catch {
      /* no token (e.g. tests) — send unauthenticated, the server decides */
    }
    const response = await fetch(url.toString(), { headers })
    if (!response.ok) {
      return null
    }
    return gvrFromCompositionDefinition(await response.json().catch(() => null))
  } catch {
    return null
  }
}

/** The denial shown when the GVR cannot be resolved — actionable, names the missing prerequisite. */
export const BUILDER_PUBLISH_GVR_DENIAL
  = 'denied — the builder-publish composition is not installed or not yet ready on this cluster '
  + '(git-provider + the builder-publish CompositionDefinition are required for SCM-agnostic publishing). '
  + 'Ask an operator to install them, or set AUTOPILOT_PUBLISH_VIA_GIT_PROVIDER="false" to use the GitHub PR path.'
