/**
 * A chart Autopilot proposes arrives WHOLE: no edge is drawn in the composer, so nothing ran
 * `planEdge`, and the edges the agent declared were drawn but never enforced when the chart rendered.
 * On arrival every node's gate is now regenerated by the same kernel — so a declared edge ends up
 * exactly as a drawn one would.
 */
import { describe, expect, it } from 'vitest'

import { applyPlan, editDescriptor, edgeChart } from '../../pages/BlueprintComposer/__fixtures__/s4b'
import { GATE_BEGIN } from '../../pages/BlueprintComposer/gateGen'
import { gateDrift, planEdge, regenerateGates } from '../../pages/BlueprintComposer/planEdge'

import { lintHeldDraft, parseProposedChart } from './proposedChart'

const LR = 'templates/localresource.yaml'

/** The fixture chart with localresource → repository DECLARED in the descriptor, but no gate written for it. */
const declaredOnly = (): Record<string, string> => editDescriptor(edgeChart(), (nodes) => nodes.map((node) => (
  node.id === 'localresource' ? { ...node, dependsOn: [...(node.dependsOn ?? []), { ref: 'repository' }] } : node
)))

describe('a proposed chart gets the gates its declared edges need', () => {
  it('writes the gate a drawn edge would have written — byte for byte', () => {
    const drawn = planEdge(edgeChart(), { from: 'localresource', op: 'add', ready: false, to: 'repository' })
    if (!drawn.ok) { throw new Error(drawn.reason) }
    const expected = applyPlan(edgeChart(), drawn)[LR]

    const declared = declaredOnly()
    expect(declared[LR]).not.toContain('"Repository"')
    const proposed = parseProposedChart(declared)
    expect(proposed?.[LR]).toContain(GATE_BEGIN)
    expect(proposed?.[LR]).toBe(expected)
  })

  it('is idempotent — a tree that already carries its gates comes back unchanged', () => {
    const once = regenerateGates(declaredOnly())
    expect(regenerateGates(once)).toBe(once)
    const chart = edgeChart()
    expect(regenerateGates(chart)).toBe(chart)
  })

  it('never touches a hand-written lookup — the tree comes back as it was, for the lint to report', () => {
    const hand = { ...declaredOnly(), [LR]: `{{- $r := lookup "v1" "ConfigMap" .Release.Namespace "x" }}\n${declaredOnly()[LR]}` }
    expect(regenerateGates(hand)).toBe(hand)
  })

  it('leaves a tree with no descriptor alone', () => {
    const tree = { 'Chart.yaml': 'apiVersion: v2\nname: plain\nversion: 0.1.0\n', 'templates/cm.yaml': 'apiVersion: v1\nkind: ConfigMap\n' }
    expect(parseProposedChart(tree)).toEqual(tree)
    expect(parseProposedChart({})).toBeNull()
  })
})

describe('declared-vs-gated drift in a held chart', () => {
  const PR = 'templates/pullrequest.yaml'
  /** edgeChart with pullrequest's gate hand-stripped in Chart files: the edge declared, nothing enforcing it. */
  const stripped = (): Record<string, string> => {
    const chart = edgeChart()
    const bare = applyPlan(chart, planEdge(chart, { from: 'pullrequest', op: 'remove', to: 'localresource' }))
    return { ...chart, [PR]: bare[PR] }
  }

  it('finds none in a chart the composer wrote — every fixture, as built', () => {
    expect(gateDrift(edgeChart())).toEqual([])
    expect(lintHeldDraft(edgeChart(), 'blueprint')).toEqual([])
  })

  it('names a template whose gate was hand-edited out, and the edge declared by hand with no gate', () => {
    expect(gateDrift(stripped())).toEqual([PR])
    expect(gateDrift(declaredOnly())).toEqual([LR])
    expect(lintHeldDraft(stripped(), 'blueprint')).toEqual([
      `${PR}: its dependency gate does not match templates/architecture.yaml — regenerate the gates, or undo the edit that changed it.`,
    ])
  })

  it('is cleared by regenerating — and a page is never linted for it', () => {
    expect(gateDrift(regenerateGates(stripped()))).toEqual([])
    expect(regenerateGates(stripped())[PR]).toBe(edgeChart()[PR])
    expect(lintHeldDraft(stripped(), 'page').some((line) => line.includes('dependency gate'))).toBe(false)
  })
})
