/**
 * A chart Autopilot proposes arrives WHOLE: no edge is drawn in the composer, so nothing ran
 * `planEdge`, and the edges the agent declared were drawn but never enforced when the chart rendered.
 * On arrival every node's gate is now regenerated by the same kernel — so a declared edge ends up
 * exactly as a drawn one would.
 */
import { describe, expect, it } from 'vitest'

import { applyPlan, editDescriptor, edgeChart } from '../../pages/BlueprintComposer/__fixtures__/s4b'
import { GATE_BEGIN } from '../../pages/BlueprintComposer/gateGen'
import { planEdge, regenerateGates } from '../../pages/BlueprintComposer/planEdge'

import { parseProposedChart } from './proposedChart'

const LR = 'templates/localresource.yaml'

/** The fixture chart with localresource → repository DECLARED in the descriptor, but no gate written for it. */
const declaredOnly = (): Record<string, string> => editDescriptor(edgeChart(), (nodes) => nodes.map((node) => (
  node.id === 'localresource' ? { ...node, dependsOn: [...(node.dependsOn ?? []), { ref: 'repository' }] } : node
)))

describe('a proposed chart gets the gates its declared edges need', () => {
  it('writes the gate a drawn edge would have written — byte for byte', () => {
    const drawn = planEdge(edgeChart(), { from: 'localresource', op: 'add', ready: false, to: 'repository' })
    if (!drawn.ok) { throw new Error(drawn.reason) }
    const expected = applyPlan(edgeChart(), drawn)[LR]

    const declared = declaredOnly()
    expect(declared[LR]).not.toContain('"Repository"')
    const proposed = parseProposedChart(declared)
    expect(proposed?.[LR]).toContain(GATE_BEGIN)
    expect(proposed?.[LR]).toBe(expected)
  })

  it('is idempotent — a tree that already carries its gates comes back unchanged', () => {
    const once = regenerateGates(declaredOnly())
    expect(regenerateGates(once)).toBe(once)
    const chart = edgeChart()
    expect(regenerateGates(chart)).toBe(chart)
  })

  it('never touches a hand-written lookup — the tree comes back as it was, for the lint to report', () => {
    const hand = { ...declaredOnly(), [LR]: `{{- $r := lookup "v1" "ConfigMap" .Release.Namespace "x" }}\n${declaredOnly()[LR]}` }
    expect(regenerateGates(hand)).toBe(hand)
  })

  it('leaves a tree with no descriptor alone', () => {
    const tree = { 'Chart.yaml': 'apiVersion: v2\nname: plain\nversion: 0.1.0\n', 'templates/cm.yaml': 'apiVersion: v1\nkind: ConfigMap\n' }
    expect(parseProposedChart(tree)).toEqual(tree)
    expect(parseProposedChart({})).toBeNull()
  })
})
