apiVersion: architecture.krateo.io/v1alpha1
kind: ChartArchitecture
chart: builder-publish
resources:
  - id: localresources
    class: custom
    apiVersion: git.krateo.io/v1alpha1
    kind: LocalResource
    template: templates/localresources.yaml
    name: printf "%s-%03d" $.Values.name (int $i) | trunc 63 | trimSuffix "-"
    forEach: builder-publish.files
    dependsOn:
      - ref: repository
        ready: true
        when: .Values.repository.create
      - ref: repo
        ready: true
        when: .Values.source.url
    readyWhen: .status.targetCommitId
  - id: pullrequest
    class: custom
    apiVersion: github.krateo.io/v2022-11-28
    kind: PullRequest
    template: templates/pullrequest.yaml
    name: printf "%s-pr" .Values.name | trunc 63 | trimSuffix "-"
    when: .Values.pullRequest.create
    dependsOn:
      - ref: localresources
        ready: true
        all: true
  - id: repo
    class: custom
    apiVersion: git.krateo.io/v1alpha1
    kind: Repo
    template: templates/repo.yaml
    name: printf "%s-source" .Values.name | trunc 63 | trimSuffix "-"
    when: .Values.source.url
    dependsOn:
      - ref: repository
        ready: true
        when: .Values.repository.create
    readyWhen: .status.targetCommitId
  - id: repository
    class: custom
    apiVersion: github.krateo.io/v2022-11-28
    kind: Repository
    template: templates/repository.yaml
    name: printf "%s-repo" .Values.name | trunc 63 | trimSuffix "-"
    when: .Values.repository.create
    readyWhen: .status.default_branch
  - id: username-secret
    class: native
    apiVersion: v1
    kind: Secret
    template: templates/username-secret.yaml
    name: printf "%s-git-username" .Values.name | trunc 63 | trimSuffix "-"
    lifecycle: shim
