/**
 * S4b's fixtures: the screen-6 chart, built the way a person builds it — Start, five placements, a
 * forEach, an edge — with every plan applied as the provider applies a batch (the architecture file's
 * graph block regenerated by the store's settle). So the chart the edge suites start from is one the
 * composer itself could have written, lint-clean, not a hand-assembled approximation of one.
 *
 *   repository     custom, github.krateo.io Repository — no readyWhen yet (screen 7 gives it one)
 *   repo           custom, git.krateo.io Repo — `when: .Values.source.url`
 *   localresource  custom, git.krateo.io LocalResource — one per item of .Values.files
 *   pullrequest    custom, github.krateo.io PullRequest — waits for every localresource to exist
 *   mongodb        composition, Mongodb v0-1-2
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { regenerateArchitecture } from '../../../components/Autopilot/blueprintDraft'
import { extractCrdSpecFields } from '../../../components/Autopilot/describeResource'
import { ARCHITECTURE_TEMPLATE_PATH, parseArchitecture, rewrapDescriptor, serializeArchitecture, unwrapFromConfigMapTemplate, type ResourceNode } from '../architecture'
import { planEdge } from '../planEdge'
import { planPlace, setForEach, type PalettePick } from '../planPlace'
import { startChart } from '../startChart'

import { CRDS } from './s4a'

type Plan = { ok: true; add?: Record<string, string>; edit: Record<string, string>; remove?: string[]; expect: Record<string, string> } | { ok: false; reason: string }

/** A plan applied as the provider applies a batch: every `expect` checked, then written, then settled. */
export const applyPlan = (files: Record<string, string>, plan: Plan): Record<string, string> => {
  if (!plan.ok) { throw new Error(`fixture plan refused: ${plan.reason}`) }
  for (const [path, bytes] of Object.entries(plan.expect)) {
    if (files[path] !== bytes) { throw new Error(`fixture plan made from stale bytes: ${path}`) }
  }
  const gone = new Set(plan.remove ?? [])
  const next = Object.fromEntries(Object.entries({ ...files, ...(plan.add ?? {}), ...plan.edit }).filter(([path]) => !gone.has(path)))
  return regenerateArchitecture(next)
}

/** A hand edit of the descriptor — what Chart files does — for what no kernel sets (a node's `when`, a lifecycle). */
export const editDescriptor = (files: Record<string, string>, change: (nodes: ResourceNode[]) => ResourceNode[]): Record<string, string> => {
  const template = files[ARCHITECTURE_TEMPLATE_PATH]
  const parsed = parseArchitecture(unwrapFromConfigMapTemplate(template) ?? '')
  if (!parsed.ok) { throw new Error(JSON.stringify(parsed.problems)) }
  const next = rewrapDescriptor(template, serializeArchitecture({ ...parsed.architecture, resources: change(parsed.architecture.resources) }))
  if (next === null) { throw new Error('no descriptor block') }
  return regenerateArchitecture({ ...files, [ARCHITECTURE_TEMPLATE_PATH]: next })
}

const REPOSITORY: PalettePick = { apiVersion: 'github.krateo.io/v2022-11-28', cls: 'custom', group: 'github.krateo.io', kind: 'Repository', plural: 'repositories' }
const REPO: PalettePick = { apiVersion: 'git.krateo.io/v1alpha1', cls: 'custom', group: 'git.krateo.io', kind: 'Repo', plural: 'repoes' }
const LOCAL_RESOURCE: PalettePick = { apiVersion: 'git.krateo.io/v1alpha1', cls: 'custom', group: 'git.krateo.io', kind: 'LocalResource', plural: 'localresources' }
const PULL_REQUEST: PalettePick = { apiVersion: 'github.krateo.io/v2022-11-28', cls: 'custom', group: 'github.krateo.io', kind: 'PullRequest', plural: 'pullrequests' }
const MONGODB: PalettePick = { apiVersion: 'composition.krateo.io/v0-1-2', blueprint: 'mongodb', cls: 'composition', kind: 'Mongodb', plural: 'mongodbs' }

/** The screen-6 chart (see the header), held under `name`. */
export const edgeChart = (name = 'orders'): Record<string, string> => {
  const started = startChart({ description: '', name, version: '0.1.0' })
  if (!started.ok) { throw new Error('fixture chart refused') }
  let { files } = started
  files = applyPlan(files, planPlace(files, REPOSITORY, extractCrdSpecFields(CRDS['repositories.github.krateo.io'], 'v2022-11-28')))
  files = applyPlan(files, planPlace(files, REPO, null))
  files = applyPlan(files, planPlace(files, LOCAL_RESOURCE, extractCrdSpecFields(CRDS['localresources.git.krateo.io'], 'v1alpha1')))
  files = applyPlan(files, planPlace(files, PULL_REQUEST, null))
  files = applyPlan(files, planPlace(files, MONGODB, null))
  files = applyPlan(files, setForEach(files, 'localresource', '.Values.files'))
  files = editDescriptor(files, (nodes) => nodes.map((node) => (node.id === 'repo' ? { ...node, when: '.Values.source.url' } : node)))
  return applyPlan(files, planEdge(files, { from: 'pullrequest', op: 'add', to: 'localresource' }))
}

/** A gated template, exactly as accepting an edge writes it. */
export const gatedGolden = (name: string): string => readFileSync(join(__dirname, 'gated', `${name}.yaml`), 'utf8')

/** The node as the held descriptor says it now. */
export const nodeIn = (files: Record<string, string>, id: string): ResourceNode => {
  const parsed = parseArchitecture(unwrapFromConfigMapTemplate(files[ARCHITECTURE_TEMPLATE_PATH]) ?? '')
  const found = parsed.ok ? parsed.architecture.resources.find((node) => node.id === id) : undefined
  if (!found) { throw new Error(`no node ${id}`) }
  return found
}
